import type { ResidentBrain, ConversationTurn } from '../brain/residentBrain.ts'

/**
 * Run a live conversation between two residents' brains, alternating turns.
 * Each line is generated by that resident's own brain (their own state, their
 * own memory of the other), on the free model tier — this is unprompted
 * background chatter, not a human-driven exchange. Both sides record the
 * finished exchange into their own persistent memory afterward.
 */
export async function converse(a: ResidentBrain, b: ResidentBrain, exchanges = 3): Promise<ConversationTurn[]> {
  const transcript: ConversationTurn[] = []
  for (let i = 0; i < exchanges; i++) {
    const lineA = await a.speakTo({ id: b.id, name: b.name }, transcript)
    transcript.push({ speaker: a.id, text: lineA })

    const lineB = await b.speakTo({ id: a.id, name: a.name }, transcript)
    transcript.push({ speaker: b.id, text: lineB })
  }

  a.recordConversation({ id: b.id, name: b.name }, transcript)
  b.recordConversation({ id: a.id, name: a.name }, transcript)

  return transcript
}
